/*
 * 	Four processes for having local output.
 *	They use js/baseprocess
 */


var MavenProcess = function() {
	var lines = [];
	lines.push("[INFO] Scanning for projects...");
	lines.push("[WARNING] ");
	lines.push("[WARNING] local problems were encountered while building the effective model for com.greatapp:local:pom:0.1-SNAPSHOT");
	lines.push("[WARNING] 'build.pluginManagement.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.phpmaven:maven-php-plugin @ org.phpmaven:php-parent-pom:2.0-SNAPSHOT, /Users/paul/.m2/repository/org/phpmaven/php-parent-pom/2.0-SNAPSHOT/php-parent-pom-2.0-SNAPSHOT.pom, line 114, column 25");
	lines.push("[WARNING] ");
	lines.push("[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.");
	lines.push("[WARNING] ");
	lines.push("[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.");
	lines.push("[WARNING] ");
	lines.push("[INFO] Building jar: /Users/paul/Projekte/revolverapp/local/frontend/target/frontend-0.1-SNAPSHOT.jar");
	lines.push("[INFO] ");
	lines.push("[INFO] --- maven-install-plugin:2.3.1:install (default-install) @ frontend ---");
	lines.push("[INFO] Installing /Users/paul/Projekte/revolverapp/local/frontend/target/frontend-0.1-SNAPSHOT.jar to /Users/paul/.m2/repository/com/greatapp/local/frontend/0.1-SNAPSHOT/frontend-0.1-SNAPSHOT.jar");
	lines.push("[INFO] Installing /Users/paul/Projekte/revolverapp/local/frontend/pom.xml to /Users/paul/.m2/repository/com/greatapp/local/frontend/0.1-SNAPSHOT/frontend-0.1-SNAPSHOT.pom");
	lines.push("[INFO] ------------------------------------------------------------------------");
	lines.push("[INFO] Reactor Summary:");
	lines.push("[INFO] ");
	lines.push("[INFO] GREAT - A webfrontend for the revolverAPP API ....... SUCCESS [0.365s]");
	lines.push("[INFO] PHP Mailer - Wrapper for PHPMailer 5.1 .............. SUCCESS [4.185s]");
	lines.push("[INFO] GREAT Backend - Webserver adapting to api ........... SUCCESS [8.271s]");
	lines.push("[INFO] GREAT frontend - The web rich client project ........ SUCCESS [12.186s]");
	lines.push("[INFO] ------------------------------------------------------------------------");
	lines.push("[INFO] BUILD SUCCESS");
	lines.push("[INFO] ------------------------------------------------------------------------");
	lines.push("[INFO] Total time: 26.515s");
	lines.push("[INFO] Finished at: Fri Sep 24 10:54:08 CEST 2012");
	lines.push("[INFO] Final Memory: 16M/265M");
	lines.push("[INFO] ------------------------------------------------------------------------");
	return BaseProcess(lines);
};

var GitProcess = function() {
	var lines = [];
	lines.push("remote: Counting objects: 37, done.");
	lines.push("remote: Compressing objects: 100% (19/19), done.");
	lines.push("remote: Total 19 (delta 12), reused 0 (delta 0)");
	lines.push("Unpacking objects: 100% (19/19), done.");
	lines.push("From ssh://revolverapp-git/great");
	lines.push("   754d496..f649e03  master     -> origin/master");
	lines.push("Merge made by the 'recursive' strategy.");
	lines.push(" .../src/main/js/components/elements/post/post.html |   58 ++++++++---");
	lines.push(" .../src/main/js/components/elements/post/post.js   |   26 +++++-");
	lines.push(" .../main/js/components/pages/analyse/analyse.js    |    6 +");
	lines.push(" .../js/components/pages/analyse/mediasegments.html |   16 +---");
	lines.push(" .../js/components/pages/analyse/sentiments.html    |   14 +---");
	lines.push(" frontend/src/main/resources/css/style.css          |  107 ++++++++++++++-----");
	lines.push(" 6 files changed, 156 insertions(+), 71 deletions(-)");
	lines.push("Pauls-MacBook-Pro:love paul$ git push");
	lines.push("Counting objects: 53, done.");
	lines.push("Delta compression using up to 8 threads.");
	lines.push("Compressing objects: 100% (28/28), done.");
	lines.push("Writing objects: 100% (28/28), 8.68 KiB, done.");
	lines.push("Total 28 (delta 15), reused 0 (delta 0)");
	lines.push("To ssh://thegreatapp-git/love");
	lines.push("   f649e03..9ebaca5  master -> master");
	return BaseProcess(lines);
};

var Git2Process = function() {
	var lines = [];
	lines.push('MacBook-Pro:terminalscreensaver paul$ subl .');
	lines.push('MacBook-Pro:terminalscreensaver paul$ git add .');
	lines.push('MacBook-Pro:terminalscreensaver paul$ git commit -m "updated processes"');
	lines.push('[master 452f0fe] updated processes');
	lines.push(' 1 files changed, 14 insertions(+), 14 deletions(-)');
	return BaseProcess(lines);
};

var LsProcess = function() {
	var lines = [];
	lines.push("-r-xr-xr-x     1 root   wheel     82688  8 Okt  2011 tconf");
	lines.push("-r-xr-xr-x     1 root   wheel     34912  8 Okt  2011 tee");
	lines.push("-r-xr-xr-x     1 root   wheel    244208  8 Okt  2011 telnet");
	lines.push("lrwxr-xr-x     1 root   wheel        78  8 Okt  2011 testrb -> ../../System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/testrb");
	lines.push("-rwxr-xr-x     1 root   wheel     28218  8 Okt  2011 texi2dvi");
	lines.push("-rwxr-xr-x     1 root   wheel    557096  8 Okt  2011 texi2html");
	lines.push("-rwxr-xr-x     1 root   wheel       660  8 Okt  2011 texi2pdf");
	lines.push("-rwxr-xr-x     1 root   wheel    109648  8 Okt  2011 texindex");
	lines.push("-rwxr-xr-x     1 root   wheel    101328 11 Feb 21:58 textutil");
	lines.push("-rwxr-xr-x     1 root   wheel     83888  8 Okt  2011 tfmtodit");
	lines.push("-r-xr-xr-x     1 root   wheel     75808  8 Okt  2011 tftp");
	lines.push("-rwxr-xr-x     1 root   wheel       418  9 Feb 21:26 thor");
	lines.push("-rwxr-xr-x     1 root   wheel    108832  8 Okt  2011 tic");
	lines.push("-rwxr-xr-x     1 root   wheel     70656  8 Okt  2011 tidy");
	lines.push("-rwxr-xr-x     1 root   wheel     47968 11 Feb 21:58 tiff2icns");
	lines.push("-rwxr-xr-x     1 root   wheel    697952 11 Feb 21:58 tiffutil");
	lines.push("-rwxr-xr-x     1 root   wheel       418  9 Feb 21:26 tilt");
	lines.push("-r-xr-xr-x     1 root   wheel     34880  8 Okt  2011 time");
	lines.push("lrwxr-xr-x     1 root   wheel        43  8 Okt  2011 tkcon -> ../../System/Library/Tcl/tkcon2.6/tkcon.tcl");
	lines.push("-rwxr-xr-x     1 root   wheel     30924  8 Okt  2011 tkmib");
	lines.push("-rwxr-xr-x     1 root   wheel    245152 16 Mai 22:45 tmdiagnose");
	lines.push("-rwxr-xr-x     1 root   wheel    465200 29 Apr 11:14 tmutil");
	lines.push("lrwxr-xr-x     1 root   wheel        79 14 Jun 10:44 tnameserv -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/tnameserv");
	lines.push("-rwxr-xr-x     1 root   wheel     49184  8 Okt  2011 toe");
	lines.push("-r-sr-xr-x     1 root   wheel    189808  8 Okt  2011 top");
	lines.push("-rwxr-xr-x     1 root   wheel    213216 11 Feb 21:58 tops");
	lines.push("-rwxr-xr-x     1 root   wheel      4619  8 Okt  2011 topsyscall");
	lines.push("-rwxr-xr-x     1 root   wheel      2950  8 Okt  2011 topsysproc");
	lines.push("-r-xr-xr-x     1 root   wheel     44016 11 Feb 22:00 touch");
	lines.push("-rwxr-xr-x     1 root   wheel     44464  8 Okt  2011 tput");
	lines.push("-r-xr-xr-x     1 root   wheel     52480  8 Okt  2011 tr");
	lines.push("-r-xr-xr-x     1 root   wheel     83792 11 Feb 22:00 trace");
	lines.push("-rwxr-xr-x     1 root   wheel      2207  8 Okt  2011 traptoemail");
	lines.push("lrwxr-xr-x     1 root   wheel        73  8 Okt  2011 trial -> /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/bin/trial");
	lines.push("-rwxr-xr-x     1 root   wheel   1106736  8 Okt  2011 troff");
	lines.push("-r-xr-xr-x     1 root   wheel     34240  8 Okt  2011 true");
	lines.push("-rwxr-xr-x     1 root   wheel     57456  8 Okt  2011 tset");
	lines.push("-r-xr-xr-x     1 root   wheel     43392  8 Okt  2011 tsort");
	lines.push("-rwxr-xr-x     1 root   wheel       425  9 Feb 21:26 tt");
	lines.push("-rwxr-xr-x     1 root   wheel     34480  8 Okt  2011 tty");
	lines.push("lrwxr-xr-x     1 root   wheel        74  8 Okt  2011 twistd -> /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/bin/twistd");
	lines.push("-r-xr-xr-x    15 root   wheel       190  8 Okt  2011 type");
	lines.push("-rwxr-xr-x     1 root   wheel     43920 11 Feb 22:00 ubcontrol");
	lines.push("-r-xr-xr-x     1 root   wheel     44256  8 Okt  2011 ul");
	lines.push("-r-xr-xr-x    15 root   wheel       190  8 Okt  2011 ulimit");
	lines.push("-r-xr-xr-x    15 root   wheel       190  8 Okt  2011 umask");
	lines.push("-r-xr-xr-x    15 root   wheel       190  8 Okt  2011 unalias");
	lines.push("-r-xr-xr-x     1 root   wheel     34800  8 Okt  2011 uname");
	lines.push("-r-xr-xr-x     2 root   wheel     52480 11 Feb 22:00 uncompress");
	lines.push("-r-xr-xr-x     1 root   wheel     35056  8 Okt  2011 unexpand");
	lines.push("-r-xr-xr-x     1 root   wheel     55952  3 Nov  2011 unifdef");
	lines.push("-r-xr-xr-x     1 root   wheel       868  3 Nov  2011 unifdefall");
	lines.push("-r-xr-xr-x     1 root   wheel     39616  8 Okt  2011 uniq");
	lines.push("-r-xr-xr-x     1 root   wheel     52240  8 Okt  2011 units");
	lines.push("lrwxr-xr-x     1 root   wheel        79 14 Jun 10:44 unpack200 -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/unpack200");
	lines.push("-r-xr-xr-x     1 root   wheel     34848  8 Okt  2011 unvis");
	lines.push("-rwxr-xr-x     1 root   wheel     84480  3 Nov  2011 unwinddump");
	lines.push("-rwxr-xr-x     2 root   wheel    261312  8 Okt  2011 unzip");
	lines.push("-rwxr-xr-x     1 root   wheel    137248  8 Okt  2011 unzipsfx");
	lines.push("-rwxr-xr-x     1 root   wheel   1419824  8 Okt  2011 update_dyld_shared_cache");
	lines.push("-r-xr-xr-x     2 root   wheel     44704  8 Okt  2011 uptime");
	lines.push("-r-xr-xr-x     1 root   wheel     34816  8 Okt  2011 users");
	lines.push("-r-xr-xr-x     1 _uucp  wheel    199872  8 Okt  2011 uucp");
	lines.push("-r-xr-xr-x     1 root   wheel     44448  8 Okt  2011 uudecode");
	lines.push("-r-xr-xr-x     1 root   wheel     39280  8 Okt  2011 uuencode");
	lines.push("-rwxr-xr-x     1 root   wheel     34912 16 Mai 22:45 uuidgen");
	lines.push("-rwxr-xr-x     1 root   wheel    143696  8 Okt  2011 uulog");
	lines.push("-r-xr-xr-x     1 _uucp  wheel     97392  8 Okt  2011 uuname");
	lines.push("-rwxr-xr-x     1 root   wheel    153088  8 Okt  2011 uupick");
	lines.push("-r-xr-xr-x     1 _uucp  wheel    220512  8 Okt  2011 uustat");
	lines.push("-rwxr-xr-x     1 root   wheel      1958  8 Okt  2011 uuto");
	lines.push("-r-xr-xr-x     1 _uucp  wheel    203952  8 Okt  2011 uux");
	lines.push("-rwxr-xr-x     1 root   wheel     73152 11 Feb 21:59 vacuumdb");
	lines.push("-rwxr-xr-x     1 root   wheel        77 12 Apr 18:42 vboxwebsrv");
	lines.push("-r-xr-xr-x     1 root   wheel      3299  3 Nov  2011 vers_string");
	lines.push("-r-xr-xr-x     1 root   wheel      3920  3 Nov  2011 vgrind");
	lines.push("lrwxr-xr-x     1 root   wheel         3  8 Okt  2011 vi -> vim");
	lines.push("lrwxr-xr-x     1 root   wheel         3  8 Okt  2011 view -> vim");
	lines.push("-rwxr-xr-x     1 root   wheel   3092160  8 Okt  2011 vim");
	lines.push("lrwxr-xr-x     1 root   wheel         3  8 Okt  2011 vimdiff -> vim");
	lines.push("-rwxr-xr-x     1 root   wheel      2084  8 Okt  2011 vimtutor");
	lines.push("-r-xr-xr-x     1 root   wheel     35072  8 Okt  2011 vis");
	lines.push("-r-xr-xr-x     1 root   wheel     43520 11 Feb 22:00 vm_stat");
	lines.push("-rwxr-xr-x     1 root   wheel     80192 11 Feb 22:00 vmmap");
	lines.push("-r-xr-xr-x     2 root   wheel     44704  8 Okt  2011 w");
	lines.push("-r-xr-xr-x    15 root   wheel       190  8 Okt  2011 wait");
	lines.push("-r-xr-sr-x     1 root   tty       49216  8 Okt  2011 wall");
	lines.push("-r-xr-xr-x     1 root   wheel     43632  8 Okt  2011 wc");
	lines.push("-rwxr-xr-x     1 root   wheel      4013  8 Okt  2011 weblatency.d");
	lines.push("-r-xr-xr-x     1 root   wheel     34512  3 Nov  2011 what");
	lines.push("-r-xr-xr-x     1 root   wheel      1806  8 Okt  2011 whatis");
	lines.push("-r-xr-xr-x     1 root   wheel     34960  8 Okt  2011 whereis");
	lines.push("-r-xr-xr-x     1 root   wheel     35008  8 Okt  2011 which");
	lines.push("-r-xr-xr-x     1 root   wheel     44016  8 Okt  2011 who");
	lines.push("-r-xr-xr-x     3 root   wheel     43856  8 Okt  2011 whoami");
	lines.push("-rwxr-xr-x     1 root   wheel     43824  8 Okt  2011 whois");
	lines.push("lrwxr-xr-x     1 root   wheel         7  8 Okt  2011 wish -> wish8.5");
	lines.push("-r-xr-xr-x     1 root   wheel       127  8 Okt  2011 wish8.4");
	lines.push("-r-xr-xr-x     1 root   wheel       127  8 Okt  2011 wish8.5");
	lines.push("-r-xr-sr-x     1 root   tty       44304  8 Okt  2011 write");
	lines.push("lrwxr-xr-x     1 root   wheel        75 14 Jun 10:44 wsgen -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/wsgen");
	lines.push("lrwxr-xr-x     1 root   wheel        78 14 Jun 10:44 wsimport -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/wsimport");
	lines.push("-rwxr-xr-x     1 root   wheel     66704  8 Okt  2011 xar");
	lines.push("-r-xr-xr-x     1 root   wheel     48656  8 Okt  2011 xargs");
	lines.push("-rwxr-xr-x     1 root   wheel       925  8 Okt  2011 xattr");
	lines.push("-rwxr-xr-x     1 root   wheel      7786  8 Okt  2011 xattr-2.5");
	lines.push("-rwxr-xr-x     1 root   wheel      9442  8 Okt  2011 xattr-2.6");
	lines.push("-rwxr-xr-x     1 root   wheel      9442  8 Okt  2011 xattr-2.7");
	lines.push("-r-xr-xr-x     2 root   wheel    110480  8 Okt  2011 xcman");
	lines.push("-rwxr-xr-x     1 root   wheel      5414 16 Mai 22:45 xcode-select");
	lines.push("-rwxr-xr-x     1 root   wheel      1086 11 Feb 22:00 xcodebuild");
	lines.push("-rwxr-xr-x     1 root   wheel      1086  3 Nov  2011 xcodeindex");
	lines.push("-rwxr-xr-x     1 root   wheel      1172 11 Feb 22:00 xcrun");
	lines.push("-rwxr-xr-x     1 root   wheel      1077 11 Feb 22:00 xed");
	lines.push("-rwxr-xr-x    26 root   wheel       807  8 Okt  2011 xgettext.pl");
	lines.push("-r-xr-xr-x     1 root   wheel      6272  8 Okt  2011 xgettext5.10.pl");
	lines.push("-r-xr-xr-x     1 root   wheel      6272  8 Okt  2011 xgettext5.12.pl");
	lines.push("-rwxr-xr-x     1 root   wheel    214880  8 Okt  2011 xgrid");
	lines.push("-rwxr-xr-x     1 root   wheel     56736 16 Mai 22:45 xip");
	lines.push("lrwxr-xr-x     1 root   wheel        73 14 Jun 10:44 xjc -> /System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/xjc");
	lines.push("-rwxr-xr-x     1 root   wheel      1819  8 Okt  2011 xml2-config");
	lines.push("-rwxr-xr-x     1 root   wheel     73792  3 Nov  2011 xml2man");
	lines.push("-rwxr-xr-x     1 root   wheel     53008 16 Mai 22:45 xmlcatalog");
	lines.push("-rwxr-xr-x     1 root   wheel    128160 16 Mai 22:45 xmllint");
	lines.push("-rwxr-xr-x     1 root   wheel     67312  8 Okt  2011 xmlwf");
	lines.push("-rwxr-xr-x    26 root   wheel       807  8 Okt  2011 xpath");
	lines.push("-r-xr-xr-x     1 root   wheel      1470  8 Okt  2011 xpath5.10");
	lines.push("-r-xr-xr-x     1 root   wheel      1470  8 Okt  2011 xpath5.12");
	lines.push("-rwxr-xr-x     1 root   wheel      2459  8 Okt  2011 xslt-config");
	lines.push("-rwxr-xr-x     1 root   wheel     67008 16 Mai 22:45 xsltproc");
	lines.push("-rwxr-xr-x     1 root   wheel       807  8 Okt  2011 xsubpp");
	lines.push("-rwxr-xr-x     1 root   wheel      4122  8 Okt  2011 xsubpp5.10");
	lines.push("-rwxr-xr-x     1 root   wheel      4122  8 Okt  2011 xsubpp5.12");
	lines.push("-rwxr-xr-x     1 root   wheel     51904  8 Okt  2011 xxd");
	lines.push("-r-xr-xr-x     1 root   wheel       135  3 Nov  2011 yacc");
	lines.push("-r-xr-xr-x     1 root   wheel     34288  8 Okt  2011 yes");
	lines.push("-r-xr-xr-x     1 root   wheel     34800  8 Okt  2011 ypcat");
	lines.push("-r-xr-xr-x     1 root   wheel     34864  8 Okt  2011 ypmatch");
	lines.push("-r-xr-xr-x     1 root   wheel     39456  8 Okt  2011 ypwhich");
	lines.push("-rwxr-xr-x     2 root   wheel    147072  8 Okt  2011 zcat");
	lines.push("-rwxr-xr-x     1 root   wheel        71  8 Okt  2011 zcmp");
	lines.push("-rwxr-xr-x     1 root   wheel      4422  8 Okt  2011 zdiff");
	lines.push("-rwxr-xr-x     1 root   wheel        66  8 Okt  2011 zegrep");
	lines.push("-rwxr-xr-x     1 root   wheel        66  8 Okt  2011 zfgrep");
	lines.push("-rwxr-xr-x     1 root   wheel      2017  8 Okt  2011 zforce");
	lines.push("-rwxr-xr-x     1 root   wheel      4894  8 Okt  2011 zgrep");
	lines.push("-rwxr-xr-x     1 root   wheel    351872  8 Okt  2011 zip");
	lines.push("-rwxr-xr-x     1 root   wheel    160224  8 Okt  2011 zipcloak");
	lines.push("-rwxr-xr-x     1 root   wheel      1188  8 Okt  2011 zipgrep");
	lines.push("-rwxr-xr-x     2 root   wheel    261312  8 Okt  2011 zipinfo");
	lines.push("-rwxr-xr-x     1 root   wheel    147232  8 Okt  2011 zipnote");
	lines.push("-rwxr-xr-x     1 root   wheel    155520  8 Okt  2011 zipsplit");
	lines.push("-rwxr-xr-x     1 root   wheel      1735  8 Okt  2011 zless");
	lines.push("-rwxr-xr-x     1 root   wheel      2441  8 Okt  2011 zmore");
	lines.push("-rwxr-xr-x     1 root   wheel      4954  8 Okt  2011 znew");
	lines.push("-r-xr-xr-x     1 root   wheel     47776 11 Feb 22:00 zprint");
	return BaseProcess(lines, 20);
};

var TestProcess = function() {
	var lines = [];
	lines.push("Running: java -classpath /Users/paul/.m2/repository/com/googlecode/jstd-maven-plugin/jstd-maven-plugin/1.3.2.7-SNAPSHOT/jstd-maven-plugin-1.3.2.7-SNAPSHOT.jar;/Users/paul/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar;/Users/paul/.m2/repository/commons-lang/commons-lang/2.5/commons-lang-2.5.jar;/Users/paul/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.0-beta-3.0.1/plexus-component-annotations-1.0-beta-3.0.1.jar;/Users/paul/.m2/repository/org/apache/xbean/xbean-reflect/3.4/xbean-reflect-3.4.jar;/Users/paul/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar;/Users/paul/.m2/repository/commons-logging/commons-logging-api/1.1/commons-logging-api-1.1.jar;/Users/paul/.m2/repository/com/google/code/google-collections/google-collect/snapshot-20080530/google-collect-snapshot-20080530.jar;/Users/paul/.m2/repository/junit/junit/3.8.2/junit-3.8.2.jar;/Users/paul/.m2/repository/org/apache/maven/artifact/maven-artifact/3.0-alpha-1/maven-artifact-3.0-alpha-1.jar;/Users/paul/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.1/plexus-utils-1.5.1.jar;/Users/paul/.m2/repository/aspectj/aspectjrt/1.5.3/aspectjrt-1.5.3.jar;/Users/paul/.m2/repository/org/codehaus/plexus/plexus-interpolation/1.1/plexus-interpolation-1.1.jar;/Users/paul/.m2/repository/org/codehaus/woodstox/wstx-asl/3.2.6/wstx-asl-3.2.6.jar;/Users/paul/.m2/repository/stax/stax-api/1.0.1/stax-api-1.0.1.jar;/Users/paul/.m2/repository/org/sonatype/spice/model-builder/1.0/model-builder-1.0.jar;/Users/paul/.m2/repository/org/apache/maven/maven-project-builder/3.0-alpha-1/maven-project-builder-3.0-alpha-1.jar -jar /Users/paul/.m2/repository/com/google/jstestdriver/jstestdriver/1.3.4.b-SNAPSHOT/jstestdriver-1.3.4.b-SNAPSHOT.jar --basePath /Users/paul/Projekte/revolverapp/love/frontend --browser /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --captureConsole --config /Users/paul/Projekte/revolverapp/local/frontend/src/test/resources/jsTestDriver.conf --port 42242 --tests all --verbose");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] JstdInitTest.testBasicLoad2");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] EventTests.test events");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] EventTests.test bind an callback to an action");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] EventTests.test bind multiple callbacks to an action");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] EventTests.test unbind an known action");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] EventTests.test callbacks can have parameters");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] EventTests.test bind to all actions from all controllers");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] EventTests.test the anonymous events knows the triggering controller");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] EventTests.test the anonymous events knows the controller and get the parameter");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test auth_token_dao instantiation");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test auth_token_dao should be logged in");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test getAuthObject should return valid auth object");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test authtokens should always be next");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test getAuthObject should always be last with multiple authtokens param");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test getAuthObject should always be last with mulitple authtokens");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test authHandler should throw exception with last token");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test authHandler should throw exception with last multiple tokens");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test reset");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test authHandler should return renew session auth object");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test authHandler return renew session auth object fail on empty auth_tokens");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test authHandler return renew session auth object fail on empty session_id");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test authHandler return renew session auth object fail on no user logged in");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test renew_session not required");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test renew_session required");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test renew_session_required after reset");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test not renew_session_required");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test singleton defined");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test singleton instance is defined");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AuthHandlerTest.test singleton is actually singleton");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] RequestTest.test action is used as unique id");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] RequestTest.test unique is overwritable");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] RequestTest.test action is writable");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] RequestTest.test deferred is created");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] RequestTest.test deferred is resolved on success");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] RequestTest.test deferred is resolved on error");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test settings loaded");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test read a setting by key");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test read a undefined setting returns undefined");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test read a value by path");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test set a value");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test set a value fires an event and pass the value");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test set a value with third parameter false will not fire an global event");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test its not possible to save values, that are not defined in the defaults");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test load settings from localStorage");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test to prevent settings from loading the saved values");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test for empty settings");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] SettingsTest.test get or default");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test module is loaded");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test instantiation");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test function requestAuthKeys exists");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test requestAuthKeys updates authtokens");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test function login exists");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test login updates authtokens");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test function post exists");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test post runs callWithAuthentication");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test function submit exists");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test function doSubmit exists");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test submit runs callWithAuthentication");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test do submit with empty options");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test do submit merges auth with options");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test do submit merges auth with options with as_user_id");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test function callWithAuthentication exists");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test not logged in causes invalidstate");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test logged out cookie inconsistence causes invalidstate");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test session_user auth_user inconsistence causes invalidstate");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test callWithAuthentication runs authentication");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test typechecking fails with numberOfAuthokens = string");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test callWithAuthentication runs renewsession");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test callWithAuthentication runs authentication for numberOfAuthTokens");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test callWithAuthentication runs renewsession for numberOfAuthTokens");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test doPost calls jQuery.ajax");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test doPost calls with valid request");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test doPost calls given success-callback");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test doPost calls given error-callback");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test callWithAuthentication runs adds as_user_id");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test synchronized renewsession sets in progress flag");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test synchronized renewsession requests in progress flag");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test synchronized renewsession respects in progress flag");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxTest.test synchronized renewsession respects in progress flag 3 times");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxUtilTest.test create empty basecontroller");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxUtilTest.test build form html without options");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxUtilTest.test build form html with options");
	lines.push("Chrome 20.0.1132.57 Mac OS [PASSED] AjaxUtilTest.test build form html with json option");
	return BaseProcess(lines, 10);
};
